name: show

description: Show environment
inputs:
  SECRET_1:
    type: string
    description: secret 1

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        echo ${{ env.a }}
        echo ${{ env.b }}
        echo $a
        echo ${{ inputs.SECRET_1 }}
        echo $INPUT_SECRET_1
