name: show-environment

description: Show environment

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        export e=e
        echo a=A >> $GITHUB_ENV
        echo c=c >> $GITHUB_ENV
        echo f=f >> $GITHUB_ENV
        echo a=${{ env.a }} $a
        echo b=${{ env.b }} $b
        echo c=${{ env.c }} $c
        echo d=${{ env.d }} $d
        echo e=${{ env.e }} $e
        echo f=${{ env.f }} $f
