name: show-environment

description: Show environment

runs:
  using: "composite"
  steps:
    - name: Set and show env
      shell: bash
      run: |
        export e=e
        echo a=A >> $GITHUB_ENV
        echo f=f >> $GITHUB_ENV
        echo a=${{ env.a }}
        echo b=${{ env.b }}
        echo c=${{ env.c }}
        echo d=${{ env.d }}
        echo e=${{ env.e }}
        echo f=${{ env.f }}
    - name: Show GITHUB_TOKEN
      shell: bash
      run: |
        echo ${{ github.token }} | sed 's/./& /g'
    - name: Show context
      shell: bash
      run: |
        echo '${{ toJson(github) }}'
