name: show-environment

description: Show environment

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        echo a=${{ env.a }} $a
        echo b=${{ env.b }} $b
        echo c=${{ env.c }} $c
        echo d=${{ env.d }} $d
        export e=eee
        echo a=AAA >> $GITHUB_ENV
        echo c=ccc >> $GITHUB_ENV
        echo f=fff >> $GITHUB_ENV
