name: show-environment

description: Show environment

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        echo ${{ env.a }}
        echo ${{ env.b }}
        echo ${{ env.c }}
        echo ${{ env.d }}
        echo $a
        echo $b
        echo $c
        echo $d
        export e=eee
        echo f=fff >> $GITHUB_ENV
