project:
  type: website

website:
  title: "My Quarto Site"
  description: "A site created with Quarto"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
  page-footer: |
      text: "Powered by Quarto"
      href: "https://quarto.org"

format:
  html:
    theme: cosmo
    toc: true
