name: md-lint

description: Run npx markdownlint-cli

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        npx markdownlint-cli '**/*.md' \
        --config '.github/workflows/.markdownlint.json' \
        --ignore '.github/CONTRIBUTING.md' \
        --ignore '.github/CODE_OF_CONDUCT.md'\
        --ignore 'CHANGELOG.md'