name: action-show

on: workflow_dispatch

env:
  a: a

jobs:
  show-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - run: ls -l
      - run: echo b=b >> $GITHUB_ENV
      - run: export c=c
      - uses: ./.github/actions/show
        env:
          d: d
      - run: |
          echo a=${{ env.a }} $a
          echo b=${{ env.b }} $b
          echo c=${{ env.c }} $c
          echo d=${{ env.d }} $d
          echo e=${{ env.e }} $e
          echo f=${{ env.f }} $f
