name: action-show

on: workflow_dispatch

env:
  a: aaa

jobs:
  show-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo b=bbb >> $GITHUB_ENV
      - run: export c=ccc
      - uses: ./.github/actions/show
        env:
          d: ddd
      - run: |
          echo a=${{ env.a }} $a
          echo b=${{ env.b }} $b
          echo c=${{ env.c }} $c
          echo d=${{ env.d }} $d
          echo e=${{ env.e }} $e
          echo f=${{ env.f }} $f
