name: boolean-input

on:
  workflow_dispatch:
    inputs:
      graphics:
        type: boolean
      tags:
        description: 'trigger manually'
  push:
    branches:
      - "release"

jobs:
  graphics:
    runs-on: ubuntu-latest
    steps:
      - name: Show github context
        run: echo '${{ toJson(github.event.inputs) }}'
      - name: Show inputs context
        run: echo '${{ toJson(inputs) }}'
      - name: call graphicstransform deploy
        if: inputs.graphics
        run: echo graphics
      - name: call graphicstransform deploy
        if: github.event.inputs.graphics == 'true'
        run: echo graphics

