name: boolean-input

on:
  workflow_dispatch:
    inputs:
      graphics:
        type: boolean
      tags:
        description: 'trigger manually'
  push:
    branches:
      - "release"

jobs:
  graphics:
    steps:
      - name: call graphicstransform deploy
        if: inputs.graphics
        run: echo graphics

