name: boolean-input

on:
  workflow_dispatch:
    inputs:
      graphics:
        type: boolean
  push:
    branches:
      - main
    paths:
      - .github/workflows/boolean-input.yaml

jobs:
  graphics:
    runs-on: ubuntu-latest
    steps:
      - name: Show github context
        run: echo '${{ toJson(github.event.inputs) }}'
      - name: Show inputs context
        run: |
          echo '${{ toJson(inputs) }}'
          echo '${{ toJson(inputs.graphics) }}'
          echo '${{ inputs.graphics || '' }}'
      - name: call if !inputs.graphics
        if: ${{ !inputs.graphics }}
        run: echo graphics
      - name: call graphicstransform deploy
        if: github.event.inputs.graphics == 'true'
        run: echo graphics
