name: branch-only-workflow

on:
  workflow_dispatch

jobs:
  dispatch:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Trigger Playwright e2e Tests workflow
        uses: actions/github-script@v6
        with:
          script: |
            const workflowName = "branch-only-workflow";

            const workflows = await github.rest.actions.listRepoWorkflows({
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            const workflow = workflows.data.workflows.find(wf => wf.name === workflowName);

            if (!workflow) {
              throw new Error(`Workflow with name '${workflowName}' not found`);
            }

            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: workflow.id,
              ref: 'main'
            });
