name: docker

on:
  workflow_dispatch

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: docker run
        run: |
          docker run --rm -d -p 8080:80 nginx
      - name: netstat
        run: |
          netstat -n| grep 8080
