name: dynakic-secret

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Setup secret names
        run: |
          echo n=1 >> $GITHUB_ENV
      - name: Read secrets
        run: |
          echo ${{ secrets[ format('SECRET_{0}', env.n) ] }} | base64
