name: if-result

on: workflow_dispatch

jobs:
  build-x:
    if: github.event.pull_request.state != 'closed' && contains(github.event.pull_request.labels.*.name, 'deploy')
    runs-on: ubuntu-latest
    steps:
      - run: echo

  build-y:
    if: github.event.pull_request.state != 'closed' && contains(github.event.pull_request.labels.*.name, 'deploy')
    runs-on: ubuntu-latest
    steps:
      - run: echo

  deploy-env:
    if: always()
    needs: [build-x, build-y]
    runs-on: ubuntu-22.04
    steps:
      - run: echo

  comment:
    if: always() && needs.deploy-env.result != 'skipped'
    needs: [deploy-env]
    runs-on: ubuntu-22.04
    steps:
      - run: echo

  result:
    if: always()
    needs: [deploy-env]
    runs-on: ubuntu-22.04
    steps:
      - run: echo ${{ needs.deploy-env.result }}
