name: java

on:
  workflow_dispatch

jobs:
  java:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '21'

    - name: Show java
      run: |
        echo $JAVA_HOME
        echo $PATH
        java -version
