name: matrix-collect-outputs

on: workflow_dispatch

jobs:
  matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: mafiapigs-macos
            metaId: 2177361
            otherId: 2177360
          - target: project-windows
            metaId: 2177362
            otherId: 2177360
    steps:
      - run: |
          matrix=$((
            echo '${{ toJSON(matrix) }}'
          ) | jq -c .)
          echo "$matrix" > matrix
          echo "::set-output name=matrix::$matrix"
        id: matrix
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ hashFiles('matrix') || 'none' }}
          path: matrix
          if-no-files-found: warn

  check-matrix:
    runs-on:  ubuntu-latest
    needs: [ matrix ]
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - uses: actions/download-artifact@v4
      - run: |
          #matrix="$(cat */matrix | jq -c --slurp .)"
          #echo "::set-output name=matrix::$matrix"
          echo matrix=$(cat */matrix | jq -c --slurp .) >> $GITHUB_OUTPUT
        id: matrix

  steam:
    name: "Release ${{ matrix.includes.target }} ${{ matrix.includes.metaId }}"
    needs: [check-matrix]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        includes: ${{ fromJSON(needs.check-matrix.outputs.matrix) }}
    steps:
      - run: echo ${{ matrix.includes.target }}
