name: multiline-body

on:
  workflow_dispatch

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Output multiline table
        id: check_repo
        run: |
          {
          echo "table<<EOF"
          echo '| a | b |
          |---|---|
          | 1 | 2 |
          '
          echo EOF
          } >> $GITHUB_OUTPUT
      - name: Create table environment
        run: |
          echo -n "table=${{ steps.check_repo.outputs.table }}" | awk '{printf "%s\\n", $0}' >> $GITHUB_ENV

      - name: Create Issue
        run: |
          issue_body='{
            "title": "Titolo",
            "body": "${{ env.table }}"
          }'

          curl -X POST -H "Authorization: token ${{ secrets.PAT }}" -d "$issue_body" https://api.github.com/repos/${GITHUB_REPOSITORY}/issues

