name: outputs

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     name: [a,b,c]
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=${{ matrix.name }}" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    environment: DEV
    needs: job1
    permissions:
      deployments: read
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
          OUTPUT2: ${{needs.job1.outputs.output2}}
        run: echo "$OUTPUT1 $OUTPUT2"
      - run: |
          echo repos/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
          gh api repos/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID/jobs
        env:
          GH_TOKEN: ${{ github.token }}
      - run: |
         echo ${{ vars.URL }}
         curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/oleg-proudnikov/actions-exam/environments/DEV/variables/URL
  

        
