name: Deploy Quarto Site to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Set up R
      #   uses: r-lib/actions/setup-r@v2

      # - name: Install R dependencies
      #   uses: r-lib/actions/setup-r-dependencies@v2
      #   with:
      #     packages: |
      #       any::tidyverse
      #       any::janitor

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Quarto site
        run: quarto render

      - name: Deploy to GitHub Pages
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
