name: Trigger auto deployment

on:
  workflow_dispatch:
  pull_request:
    types: ["opened", "edited", "reopened", "synchronize", "ready_for_review"]

jobs:
  fail_if_pull_request_is_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Simple step
        run: echo Done!