name: Trigger auto deployment

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches:
      - main
  # Allow manual trigger
  workflow_dispatch:
  pull_request:
    types: ["opened", "edited", "reopened", "synchronize", "ready_for_review"]

jobs:
  fail_if_pull_request_is_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Simple step
        run: echo Done!