name: sarif
on: workflow_dispatch

jobs:
  sarif:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ./vulnerabilities-results.sarif
