    name: service
    on: workflow_dispatch

    jobs:
      setup:
        runs-on: ubuntu-latest
        outputs:
          image: ${{ steps.set.outputs.image }}
        steps:
          - id: set
            run: echo "image=redis" >> "$GITHUB_OUTPUT"

      container-job:
        needs: setup
        runs-on: ubuntu-latest
        container: node:18

        services:
          redis:
            image: ${{ needs.setup.outputs.image }}

        steps:
          - name: Install Redis CLI
            run: |
              apt-get update
              apt-get install -y redis-tools
          - name: Check Redis service
            run: |
              redis-cli -h redis -p 6379 ping
