name: show

on:
  workflow_dispatch:

  workflow_call:
    secrets:
      SECRET:
        description: secret

jobs:
  show:
    if: ${{ !(github.event.workflow_run) }}
    runs-on: ubuntu-latest
    steps:
      - name: Show env
#        shell: bash
        run: |
          echo a=${{ env.a }}
          echo b=${{ env.b }}

      - name: Show Secrets
#        shell: bash
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | sed 's/./& /g'
          echo ${{ secrets.SECRET }} | sed 's/./& /g'

