name: show

on:
  workflow_dispatch:

  workflow_call:
    secrets:
      SECRET:
        description: secret

jobs:
  show:
    runs-on: ubuntu-latest
    steps:
      - name: Set and show env
        shell: bash
        run: |
          echo a=${{ env.a }}
          echo b=${{ env.b }}

          echo a=A >> $GITHUB_ENV
          echo c=c >> $GITHUB_ENV

      - name: Show GITHUB_TOKEN
        shell: bash
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | sed 's/./& /g'
          echo ${{ secrets.SECRET }} | sed 's/./& /g'

