name: Skip

on:
  workflow_dispatch:

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - run: echo job-1
  
  job-2:
    needs: job-1
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
  
  job-3:
    if: false
    needs: job-2
    runs-on: ubuntu-latest
    steps:
      - run: echo job-3
  
  job-4:
    needs: job-3
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: echo job-4
  
