name: Skip

on:
  workflow_dispatch:

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
    - id: step1
      run: echo "test=hello" >> "$GITHUB_OUTPUT"
    - id: step2
      run: echo test=${{ steps.step1.outputs.test }}

  job-2:
    needs: job-1
    runs-on: ubuntu-latest
    steps:
      - run: exit 0

  job-3:
    if: false
    needs: job-2
    runs-on: ubuntu-latest
    steps:
      - run: echo job-3

  job-4:
    needs: [job-2, job-3]
    if: needs.job-2.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - run: echo job-4

