    name: trigger-main-to-branch

    on:
      push:
        branches: '**'
      workflow_dispatch:

    jobs:
      main:
        runs-on: ubuntu-latest
        if: github.ref_name == github.event.repository.default_branch
        permissions:
          contents: read
          workflow: write
        steps:
          - name: Build main
            run: echo Build main branch
          - name: Trigger feature branch build
            run: |
              echo Trigger feature branch build
              gh workflow run --ref feature-a trigger-main-to-branch
            env:
              GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      feature:
        runs-on: ubuntu-latest
        if: github.ref_name != github.event.repository.default_branch
        steps:
          - name: Build feature branch
            run: echo Build feature branch
