name: venv

on:
  workflow_dispatch:

jobs:
  install-dependency:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.9'

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install requests
          ls -l
          ls -l venv

      - uses: actions/upload-artifact@v4
        with:
          name: venv
          path: ./venv
    
  run-pytest:
    runs-on: ubuntu-latest
    needs: [install-dependency]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.9'

      - run: |
          pwd
          echo $GITHUB_WORKSPACE
          
      - uses: actions/download-artifact@v4
        with:
          name: venv
          path: ./venv

      - run: |
          ls -l
          ls -l venv

      - name: Activate
        run: source venv/bin/activate


  run-other-pytest:
    runs-on: ubuntu-latest
    needs: [install-dependency]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.9'

      - uses: actions/download-artifact@v4
        with:
          name: venv
          path: ./venv

      - run: |
          ls -l
          ls -l venv
          
      - name: Activate
        run: source venv/bin/activate

