name: workflow-skipped
on:
  workflow_dispatch:

run-name: |
  ${{ contains(github.event.issue.labels.*.name, 'bug') ||
  contains(github.event.issue.labels.*.name, 'dependencies') ||
  contains(github.event.issue.labels.*.name, 'enhancement') }}

jobs:
  fail:
    runs-on: ubuntu-latest
    if: false

    steps:
      - run: echo Never run

  pass:
    needs: fail
    runs-on: ubuntu-latest
    if: needs.fail.outcome != 'skipped' && false

    steps:
      - run: echo Never run
