name: workflow1
on:
  workflow_dispatch:

  workflow_call:

  secrets:
    SECRET_1:
      deascription: secret 1

jobs:
  deploy:
    name: Import external glossaries
    runs-on: ubuntu-latest

    steps:
      - shell: bash
        run: |
          echo ${{ env.a }}
          echo $a
          echo ${{ secrets.SECRET_1 }}
