name: workflow2
on:
  workflow_dispatch:

  workflow_call:

jobs:
  deploy:
    name: Import external glossaries
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      ##############################
      - name: Import external glossaries
        run: echo workflow2 > workflow2.txt
      ##############################



      ##############################
      - name: Commit and push the changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/oleg-proudnikov/actions-exam.git

          git add .
          git commit -m "chore: fetch content from various external sources"
          git push
          git status
