name: workflow-show

on: workflow_dispatch

env:
  a: a

jobs:
  env-1:
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: |
          echo b=b >> $GITHUB_ENV
      - name: Show Secrets
        shell: bash
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | sed 's/./& /g'
          echo ${{ secrets.SECRET }} | sed 's/./& /g'

  env-2:
    needs: env-1
    uses: ./.github/workflows/show.yaml
    secrets:
      SECRET: ${{ secrets.SECRET }}
