name: workflow_main

on:
  workflow_dispatch:

jobs:
  workflow1:
    uses: ./.github/workflows/workflow1.yaml
    secrets: inherit

  workflow2:
    needs: workflow1
    uses: ./.github/workflows/workflow2.yaml
    secrets: inherit
