name: workflow-show

on: workflow_dispatch

env:
  a: a

jobs:
  env-1:
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: |
          echo b=b >> $GITHUB_ENV
          export c=c

  env-2:
    needs: env-1
    uses: ./.github/workflows/show.yaml
    secrets:
      SECRET: ${{ secrets.GITHUB_TOKEN }}

  env-3:
    needs: env-2
    runs-on: ubuntu-latest
    steps:
      - name: Show env
        run: |
          echo a=${{ env.a }}
          echo b=${{ env.b }}
          echo c=${{ env.c }}
          echo d=${{ env.d }}
          echo e=${{ env.e }}
      - name: Show GITHUB_TOKEN
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | sed 's/./& /g'
      - name: Show context
        run: |
          echo '${{ toJson(github) }}'
