name: workflow1
on:
  workflow_dispatch:

  workflow_call:

jobs:
  deploy:
    name: Import external glossaries
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - shell: bash
        run: |
          echo ${{ env.a }}
          echo $a
          echo ${{ secrets.SECRET_1 }}
